### ISSUE TITLE
How to plot the tree for a survival tree.

### ISSUE THREAD

**Issue by anirbanmishra** [sebp/scikit-survival#133] opened 2020-07-20 19:03 UTC
I got the estimator using :
estimator = SurvivalTree().fit(X_train, y_train)

But when I use tree.plot_tree I get an error stating the following:

AttributeError: 'SurvivalTree' object has no attribute 'criterion'

I tried graphviz too and get the same error.

So basically I want the survival tree to be plotted for better interpretation.

**Comment by sebp** [comment] 2020-07-21 07:00
Duplicate of #110

**Closed by sebp** 2020-07-21 07:00 UTC
