### ISSUE TITLE
function  rsf.score  make whole program crashed 

### ISSUE THREAD

**Issue by undersunshine** [sebp/scikit-survival#147] opened 2020-10-22 06:21 UTC
**Describe the bug**

When I trained the model, got the model and then wanted to test the model with function rsf.score, the whole python program would go crash and I need to restart the python kernel. The size of the testing dataset is about (700k， 30). 

**Code Sample to Reproduce the Bug**

```python
rsf.score(X_test, y_test)
```

**Comment by sebp** [comment] 2020-10-22 06:34
Please provide a full description of the problem, including a full 
minimal example to reproduce the crash and a complete traceback of the 
crash.

**Comment by undersunshine1020** [comment] 2020-10-22 09:29
Thanks for your reply!

I tried several examples, and find that the minimal size to reproduce the crash is about 355000 x 32. 

On the web, people says the crashed phenomenon is due to computer's memomy.

I use the jupyter notebook to run program. The jupyter is from my company's server. Sorry for I don't know how to traceback completely.
When the program crashed, the web would show like this:

![企业微信截图_16033567027922](https://user-images.githubusercontent.com/15973878/96852046-4248a980-148b-11eb-80eb-66a0af343188.png)

So I wonder if function rsf.score takes up too much memory when it runs.

**Comment by sebp** [comment] 2020-10-22 13:06
Unfortunately, the screenshot doesn't provide any hints on what the 
cause was. The juypter notebook might output more information on the 
terminal (on the server running jupyter). An out of memory error could 
be one possibility.

**Comment by undersunshine** [comment] 2020-10-23 01:36
Ok, thanks for reply. I don't have access to the terminal. I would try it on my own computer later and hope to find some clue.

**Comment by sebp** [comment] 2020-12-01 18:02
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.

**Closed by sebp** 2020-12-01 18:02 UTC
Labels: awaiting response
