### ISSUE TITLE
Support scikit-learn >=1.2

### ISSUE THREAD

**Issue by tom-mcclintock** [sebp/scikit-survival#335] opened 2023-01-12 23:19 UTC
Sklearn [v1.2.0 ](https://pypi.org/project/scikit-learn/)released on Dec 8, and the Oct 24 release of sksurv pinned the upper bound to [<1.2](https://github.com/sebp/scikit-survival/blob/master/requirements/prod.txt#L8).

**Describe the solution you'd like**
Attempt to open the upper bound on the dependency and cut a new release.

**Comment by dpellow** [comment] 2023-02-01 15:56
@tom-mcclintock Does it work with scikit-learn 1.2?
I am using sklearn 1.2.1 (need >= 1.2 for other functionality) but when I run the RSF I get a number of Runtime warnings:
```
<frozen importlib._bootstrap>:228: RuntimeWarning: sklearn.tree._criterion.Criterion size changed, may indicate binary incompatibility. Expected 328 from C header, got 528 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: sklearn.tree._splitter.Splitter size changed, may indicate binary incompatibility. Expected 1160 from C header, got 1360 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: sklearn.tree._criterion.ClassificationCriterion size changed, may indicate binary incompatibility. Expected 1168 from C header, got 1368 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: sklearn.tree._criterion.RegressionCriterion size changed, may indicate binary incompatibility. Expected 960 from C header, got 1160 from PyObject
```
And then when it reaches fit() there is a python MemoryError and the message `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`.

I believe the first Runtime warnings are because of the sklearn version? Is this what is causing the MemoryError?

Here is more of the error message that is output:
```
  File "/home/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_search.py", line 874, in fit
    self._run_search(evaluate_candidates)
  File "/home/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_search.py", line 1388, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/home/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_search.py", line 821, in evaluate_candidates
    out = parallel(
  File "/home/anaconda3/lib/python3.9/site-packages/sklearn/utils/parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
  File "/home/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/homel/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
  File "/home/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/sklearn/utils/parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/anaconda3/lib/python3.9/site-packages/sklearn/pipeline.py", line 405, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/home/anaconda3/lib/python3.9/site-packages/sksurv/ensemble/forest.py", line 144, in fit
    trees = Parallel(n_jobs=self.n_jobs, verbose=self.verbose,
  File "/home/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/anaconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
  File "/home/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 184, in _parallel_build_trees
    tree.fit(X, y, sample_weight=curr_sample_weight, check_input=False)
  File "/home/anaconda3/lib/python3.9/site-packages/sksurv/tree/tree.py", line 253, in fit
building tree 1 of 100
    builder.build(self.tree_, X, y_numeric, sample_weight)
  File "sklearn/tree/_tree.pyx", line 147, in sklearn.tree._tree.DepthFirstTreeBuilder.build
  File "sklearn/tree/_tree.pyx", line 219, in sklearn.tree._tree.DepthFirstTreeBuilder.build
  File "sklearn/tree/_splitter.pyx", line 182, in sklearn.tree._splitter.Splitter.node_reset
  File "sksurv/tree/_criterion.pyx", line 154, in sksurv.tree._criterion.LogrankCriterion.init
MemoryError
```

I would appreciate any help in debugging this and getting it to work. Thanks!

**Comment by tom-mcclintock** [comment] 2023-02-01 16:00
@dpellow I don't know. I didn't try changing the upper bound manually.

However, your error appears to be a loading version issue. The initial warnings, were they generated when you instantiated a new object, or were you loading a model from memory? Since the errors are `joblib` and memory size related, my hunch is the latter.

**Comment by dpellow** [comment] 2023-02-01 16:10
Thanks. When I installed sksurv it downgraded my sklearn. I then manually upgraded back to v1.2.1 for the other functionality I need. 

I believe the initial warnings are from when I import RSF from sksurv.

I think the messages about joblib errors are just the sksurv memoryerror propagating back up into my sklearn pipeline. I'm wondering if the memoryerror is caused by incompatibility with my version of sklearn or if there is something else going wrong.

**Comment by sebp** [comment] 2023-02-01 17:09
I started working on adding support for sklearn 1.2 in the [sklearn-12 branch](https://github.com/sebp/scikit-survival/tree/sklearn-12).

It compiles and seems to work, but I still want to adapt sklearn's [new way](https://github.com/scikit-learn/scikit-learn/issues/23462) of validating model parameters.

**Comment by sebp** [comment] 2023-02-15 20:26
@dpellow I'm still working on it, but I expect it to be ready to be merged soon. If you feel adventurous, you can try installing sksurv from the sklearn-12 branch.

**Closed** 2023-02-26 21:49 UTC
Labels: dependencies

**Comment by dpellow** [comment] 2023-02-27 13:27
Awesome! will it be released on conda/pypi?

**Comment by sebp** [comment] 2023-02-27 17:36
Yes. Hopefully I can push a new release this week.
