### ISSUE TITLE
CoxPH SurvivalAnalysis and Singular Matrix Error

### ISSUE THREAD

**Issue by sarahysh12** [sebp/scikit-survival#28] opened 2018-03-05 21:39 UTC
I'm going through the tutorial using the veterans lung cancer study and I am using the same code for my own dataset for Cox regression. My problem is to calculating the days to graft failure after a transplant and the dataset has about 900 features after encoding and other preprocessing steps and it has 130K rows. I prepared data for Cox regression (data_x is a dataframe and data_y is a numpy array of status and suvival_in_days) and took a sample of it to run. However when I run the CoxRegression, I am getting the error of:
LinAlgError:Matrix is Singular
I manipulated my data in different ways, but I could not understand what is the problem and how to solve it.

**Comment by vfa-phuclkh** [comment] 2018-03-06 01:59
It's depend on the data but I guess you have some One-hot vectors features. Try to remove those features and see if the problem disappear, at least that was my case.

**Comment by sarahysh12** [comment] 2018-03-06 18:13
@vfa-phuclkh Yes, half of my features were categorical and I encoded them with one-hot encoding. The veterans lung cancer also had two One-hot features, so I thought it should work. What if I don't want to remove the categorical features? I cannot remove them without any reason since it is a medical problem and I need accurate results.

**Comment by sebp** [comment] 2018-03-06 20:33
@sarahysh12 The standard Cox regression fails if features are highly correlated. I'd suggest you set alpha to a small positive value such as 0.0001 or use CoxnetSurvivalAnalysis.

**Comment by sarahysh12** [comment] 2018-03-07 23:51
@sebp I will try CoxnetSurvivalAnalysis. However, I set alpha to 0.0001 and I got this error. I don't have any Nan in my data. Do you have any idea?
`estimator.fit(data_x, data_y)
/anaconda/lib/python3.6/site-packages/sksurv/linear_model/coxph.py:68: RuntimeWarning: divide by zero encountered in log
  loss -= (xw[i] - numpy.log(risk_set)) / n_samples
/anaconda/lib/python3.6/site-packages/sksurv/linear_model/coxph.py:105: RuntimeWarning: invalid value encountered in true_divide
  gradient -= (x[i:i + 1] - risk_set_x / risk_set) * inv_n_samples
/anaconda/lib/python3.6/site-packages/sksurv/linear_model/coxph.py:107: RuntimeWarning: invalid value encountered in true_divide
  a = risk_set_xx / risk_set
/anaconda/lib/python3.6/site-packages/sksurv/linear_model/coxph.py:108: RuntimeWarning: invalid value encountered in true_divide
  z = risk_set_x / risk_set
Traceback (most recent call last):

  File "<ipython-input-20-4f71f18578b3>", line 1, in <module>
    estimator.fit(data_x, data_y)

  File "/anaconda/lib/python3.6/site-packages/sksurv/linear_model/coxph.py", line 211, in fit
    raise ValueError("search direction contains NaN or infinite values")

ValueError: search direction contains NaN or infinite values`

**Comment by pavopax** [comment] 2018-03-13 07:46
double check NaNs with `df.isnull().sum().sum()` and `df.isnull().sum()`

Cox Net docs are here: https://scikit-survival.readthedocs.io/en/latest/generated/sksurv.linear_model.CoxnetSurvivalAnalysis.html

**Comment by sebp** [comment] 2018-03-13 21:07
Checking for NaN in the input is a good idea. In addition, you can use `CoxPHSurvivalAnalysis` with `verbose=10` to find out weather the optimization generates NaN eventually.

**Comment by sebp** [comment] 2018-07-02 20:54
I'm closing this issue as no further information has been provided. Please feel free to reopen this issue if you can provide the requested information.

**Closed by sebp** 2018-07-02 20:54 UTC
Labels: awaiting response

**Comment by nd26** [comment] 2019-10-28 16:16
I've come across the same error status as @sarahysh12 
"ValueError: search direction contains NaN or infinite values"

When I used verbose=10 (@sebp), I get the following:
```
iter      1: update = [-1.32286065e-02  8.41704162e-02 -7.61110478e-02  2.06318149e-02
 -4.15423521e-02  8.79209202e-02  1.28655285e-01  5.92193763e-01
 -8.54131979e-01 -1.08310140e-02  1.43972502e-02 -5.04341829e-02
 -1.44140870e-01 -7.13594339e-01  8.88186021e-01 -1.46392842e-01
  3.05045366e-01 -6.32151193e+00  5.65144984e-02 -7.85622389e-02
 -4.10658884e-02  3.50364529e-02 -4.09453088e-02 -7.48989392e-02
 -5.55312494e-02 -5.72540845e-01  9.78664659e-02 -1.81549048e+00
 -8.32754216e+00  3.07044711e-01 -1.56170258e+00  5.11963454e+00
 -2.41157002e+00  6.18206650e-02  5.06796879e-01  7.83965871e-01
  2.56195996e+03 -1.04704718e+03  8.34629588e+02  1.09987679e+01
 -1.18857496e+02 -3.69577435e+02 -5.21440086e-01 -3.75192857e-01
 -7.01361213e-01  3.77293014e+03 -1.29486162e+03  7.31302400e+03
  1.03985696e-02 -3.42706765e-02  9.68237894e-02 -3.84213836e-03
  1.67116211e-02  4.79190287e-03  1.64455995e-03  5.70096198e-03
 -8.73368786e-03  1.67447521e+02  5.15133559e+01  4.30791640e+02
 -3.03930186e+02  2.46160751e+03  2.33011405e+04  1.19378792e+03
  3.23742366e+02 -4.22526500e+02 -2.75877351e-02 -2.80472334e-01
  2.47461219e-01  6.23025527e-02  7.00387953e-04 -1.49468742e-02
 -8.53531247e-05  1.31966949e-02  3.15185194e-03 -2.87214788e-02
 -1.46871572e-02  2.92811365e-02 -6.98242306e-02  1.05301708e+00
 -1.43233636e+00  5.69134328e-01  2.16962882e-01 -6.55460356e-01
  9.42634949e-01  3.20136086e+00 -1.64871812e-01  1.14692600e-01
  1.32007164e-01 -3.50741365e-01 -2.40748556e-02 -7.92291259e-02
 -1.37123275e-02 -1.31263298e+02  2.00694139e+00  1.13368668e+02
 -4.93416987e+02  4.44377501e+01  2.36883852e+02 -4.01681225e+03
 -1.33881593e+03  4.89986879e+03 -7.08064166e-03 -4.93220308e-03
  9.12453181e-03  2.95286716e-03 -2.08922329e-02  4.43865386e-03
  3.61652064e-03  9.21088656e-03 -1.86076526e-03 -1.30858996e+00
  1.76082596e+00  3.78570792e-01 -9.88692408e-02  4.60982409e-02
 -3.65634101e-02 -7.37193662e+02 -1.06513495e+03  3.23712775e+02
 -8.58339615e+02 -2.90661548e+02 -1.14601985e+03  2.45774187e+03
 -7.74015225e+02 -1.17012239e+03  7.10586047e+00 -6.51284535e+03
 -7.17867288e+03  1.02941450e+01  1.35862601e+03  1.66802549e+03
 -1.13353672e+03 -9.10230999e+01 -5.68948586e+02  4.75301308e+03
  6.56896672e+03  2.25069671e+03  2.90275043e+02  7.72557883e+02
 -1.93861640e+03]
iter      1: loss = inf
```
Any idea why this is happening? Thank you.

**Comment by nd26** [comment] 2019-10-28 16:17
Also, @sebp when I set the alpha to 0.00001:

```
iter      1: update = [-1.43010747e-02 -5.97101453e-02  3.18295279e-02  1.82974853e-03
  4.29211641e-02 -7.07834176e-02 -4.78870838e-02 -1.21322531e-02
  1.63986775e-01 -3.85490013e-03 -5.16328726e-02  7.64600603e-02
  6.72477720e-02  7.09466385e-02 -1.59867371e-01 -1.31525014e-01
  2.27771333e-02 -4.48655383e-01 -1.21110447e-01 -1.17597714e-02
  2.59559356e-01  1.21641631e-01 -1.19378006e-02 -1.76192908e-01
  1.57207606e-01  9.17110537e-01 -6.68984382e-01 -4.20844136e-01
 -1.44283971e+00  1.05831532e+00  6.55602158e-01 -1.07364928e+00
  1.63529391e-01 -1.67345270e-01 -5.84448980e-01  3.92908650e-01
 -3.96922474e-02 -2.29870815e-02  4.36496539e-02  2.31121079e+00
  3.98757075e-01  5.54296208e-01 -8.01140054e-02  1.33444638e-01
 -1.96630809e-02  3.11342467e-01  1.79135885e-01  4.36868046e-02
  1.54894419e-02 -4.12265602e-02 -2.04527960e-02  1.57316196e-02
 -4.14118721e-02 -1.32859855e-02 -1.47168429e-02  4.30278985e-02
  1.21865263e-02  4.38763873e-02  3.17360971e-04  1.00915362e-01
 -1.33304387e-02 -2.89985209e-02  1.19459160e-03  5.72045291e-02
  2.92845096e-02  9.98859216e-02 -4.23925623e-03  3.99899159e-02
 -4.07715383e-03 -3.52627640e-02  3.09699755e-03  5.28666541e-02
  1.34639556e-02  3.50021068e-03 -2.08709724e-02  7.87596564e-03
 -2.82271632e-02 -1.20003975e-01  1.21015069e-01 -2.49657883e-01
  1.93998127e-01 -4.21335576e-03 -3.70796255e-01 -1.60050099e+00
 -3.62234174e-01  7.52370575e-01 -6.38812359e-02 -2.54950913e-02
  9.25240555e-02 -1.37841737e-01  2.57160509e-02 -2.05452903e-04
  2.10703833e-02 -1.32138478e+00 -1.48717550e+00 -1.45492849e+00
 -6.05323883e-01 -3.38475807e-01  5.94555185e-01  3.20455517e-01
  1.85302401e-01  7.75346876e-02  1.31347162e-02  2.46023977e-02
  3.58417755e-03  1.18987589e-02  2.82884106e-02  4.25041910e-04
 -1.27953638e-02 -3.01615524e-02  3.18628432e-03  1.39957960e-01
 -2.57704284e-01  1.98606411e+00  3.58508695e-02  5.92658988e-03
 -7.20326025e-02 -2.79688186e-01  2.89981447e-02  1.38787167e-01
 -1.46161464e-01 -2.59078774e-02  1.24634104e-02 -1.33529916e-01
  5.49168822e-02  1.26322564e-01  7.20695898e-01 -7.02069661e-01
  7.02071267e-01  4.02567984e-01  8.05686466e-02 -4.83140656e-01
 -4.06158760e-02  9.89202657e-02 -5.83020835e-02  4.60819635e-01
 -4.60819127e-01  4.21062448e-01  1.36652069e-01 -9.69000826e-02
 -4.60817225e-01]
iter      1: loss = 0.7841787771
iter      2: update = [ 1.02986296e-02  5.15485441e-02 -1.82338889e-02  2.81643304e-02
  5.43607977e-04  3.20436656e-02  4.47040173e-02  1.52674401e-02
 -1.78295509e-01 -2.63044081e-02  7.51761511e-03 -3.73126640e-02
 -1.00249949e-01 -7.34458746e-02  2.06620380e-01  2.61759569e-01
 -1.78612804e-02  2.27019110e-01  2.54794053e-01  1.20208793e-02
 -1.48769977e-01 -2.52898870e-01  1.76999766e-02  8.59113306e-02
 -2.15420625e-01 -8.71899780e-01  6.21632679e-01  5.72237057e-01
  1.31696484e+00 -9.39463089e-01 -6.68765725e-01  7.07813459e-01
 -2.50302791e-01  2.23549923e-01  5.38580189e-01 -3.44679245e-01
  4.65462982e-02  2.58963048e-02 -4.39170827e-02 -2.31151675e+00
 -3.78732661e-01 -5.30998575e-01  7.69058529e-02 -1.32627131e-01
  1.41946295e-02 -3.14127906e-01 -1.88269894e-01 -4.67767641e-02
  1.72573622e-02  3.26171072e-02  1.61787153e-02  1.66099494e-02
  3.28901966e-02  3.03029803e-03 -1.75595117e-02 -3.44435918e-02
 -2.34459469e-03 -4.41254390e-02  9.63377716e-05 -1.03398689e-01
  1.52301862e-02  3.03708515e-02 -1.32001945e-03 -5.93585902e-02
 -3.02418715e-02 -1.02306983e-01  1.18619469e-02 -2.96634610e-02
 -1.69234300e-02  3.00534154e-02  1.28705260e-02 -5.04908170e-02
 -1.22045161e-02 -4.75277540e-03  1.81324918e-02 -1.91517614e-03
  3.35599799e-02  1.20951102e-01 -1.33660129e-01  2.42191492e-01
 -1.56696791e-01 -1.57819385e-02  5.59999823e-01  1.77038870e+00
  3.45421538e-01 -8.37403018e-01  1.69099225e-01  1.84529949e-02
 -8.69686879e-02  1.38731455e-01 -2.33087639e-02 -1.49592159e-02
 -4.81802578e-02  1.37490585e+00  1.43273072e+00  1.46722464e+00
  6.41194934e-01  3.41715380e-01 -6.06930767e-01 -3.23701279e-01
 -1.94450839e-01 -8.30608694e-02  1.63850307e-03 -1.09579079e-02
  2.25624171e-02  3.45208982e-03 -1.40946697e-02  2.59265976e-02
 -2.71161820e-03  1.61334007e-02 -2.86646142e-02 -1.50925991e-01
  1.00139121e-01 -2.09404283e+00 -3.00183019e-02 -2.49045123e-02
  6.93040841e-02  3.02639261e-01 -2.86168309e-02 -1.46388106e-01
  1.58718087e-01  3.02419087e-02 -1.27367519e-02  1.43923381e-01
 -5.88673173e-02 -1.33653083e-01 -6.05695519e-01  7.61354050e-01
 -7.61352510e-01 -3.48179590e-01 -1.20623827e-01  4.68810163e-01
  5.72982189e-02 -1.13092980e-01  5.57952674e-02 -4.49140298e-01
  4.49143351e-01 -3.74416099e-01 -1.73824985e-01  9.91043450e-02
  4.49144066e-01]
iter      2: loss = 5.2036295206
iter      1: loss increased, performing step-halving. loss = 1.1092974200
iter      3: update = [ 3.52528997e-03  2.03682898e-02 -6.12574367e-03 -4.29530300e-04
 -1.12434057e-03  6.15786928e-02  2.08831183e-02  1.18971375e-03
 -7.06540479e-02  9.93707485e-04  4.57321318e-03 -6.36982802e-02
 -3.36160375e-02 -4.54147629e-03  2.95844886e-02  2.51489195e-02
 -1.22993874e-02  3.30793836e-02  2.51768361e-02 -2.89220782e-03
 -1.11171644e-02 -2.40179224e-02  1.84187974e-02 -7.97994201e-03
 -1.10946980e-01 -3.57504032e-01  2.55618628e-01  3.25415057e-01
  5.37423396e-01 -3.89254082e-01 -3.28768135e-01  1.07404636e-01
 -1.02691776e-01  1.17659005e-01  2.19556361e-01 -1.38815453e-01
  2.60201721e-02  1.54005860e-02 -1.19847309e-02 -1.13280279e+00
 -1.45696645e-01 -1.76227046e-01  2.68746485e-02 -5.44527710e-02
  5.55619143e-03 -1.41062228e-01 -8.77453380e-02 -2.19294015e-02
  3.11929623e-03  1.53912260e-03  3.52520117e-03  2.79308329e-03
  1.59801704e-03 -2.82218758e-03 -3.13700792e-03 -2.25856592e-03
  3.03415043e-03 -1.88152733e-02  3.88239373e-03 -4.57741368e-02
  7.66866691e-03  1.59473650e-02 -5.23062533e-04 -2.64838206e-02
 -1.20477383e-02 -4.53585150e-02  5.76180791e-03 -1.10711176e-02
 -8.86385615e-03  1.15132675e-02  9.09678389e-03 -1.94063845e-02
 -4.54161006e-03 -2.32989142e-03  6.60237448e-03 -3.19374486e-03
  2.17266417e-02  5.27163208e-02 -5.35439468e-02  9.32244936e-02
 -4.49451873e-02 -2.75141380e-02  2.65971055e-01  7.22905654e-01
  1.66780235e-01 -3.99900376e-01  1.33704242e-01  9.12807004e-03
 -3.93461090e-02  4.40422399e-02 -4.04189381e-03 -1.88644679e-02
 -3.24217209e-02  5.85314384e-01  5.41566569e-01  5.89503009e-01
  3.14208725e-01  1.57655996e-01 -2.85448999e-01 -1.46381932e-01
 -9.29710227e-02 -4.00137197e-02 -6.59689645e-03 -1.57824270e-04
  1.05947031e-02 -5.74493431e-03 -1.22438961e-03  1.20326666e-02
  6.03129766e-03  2.04558732e-03 -1.29480042e-02 -6.06125741e-02
  1.61751861e-02 -8.49792274e-01 -1.16379627e-02 -1.44116230e-02
  2.66397662e-02  1.48456267e-01 -1.11498424e-02 -6.90012306e-02
  7.71834171e-02  1.59858431e-02 -5.88578617e-03  7.12806988e-02
 -2.71413366e-02 -6.31147580e-02 -2.62378520e-01  3.77526753e-01
 -3.77527998e-01 -1.39961399e-01 -4.14995229e-02  1.81462509e-01
  3.61748247e-02 -6.18861530e-02  2.57103760e-02 -1.70508502e-01
  1.70508396e-01 -1.52780139e-01 -6.42755341e-02  4.65503383e-02
  1.70506600e-01]
iter      3: loss = 0.9045874441
iter      4: update = [-1.83898912e+03 -8.57927188e+03  3.83589162e+03 -7.25820104e+03
  6.10029819e+03 -1.09052789e+04 -7.72163543e+03 -1.64147902e+03
  2.68033697e+04  6.97602068e+03 -7.48682108e+03  1.17843291e+04
  1.85758464e+04  8.20608470e+03 -2.60543144e+04 -9.94628011e+03
  2.50714721e+03 -5.08992087e+04 -9.08563356e+03 -2.31471053e+03
  3.09877081e+04  8.90030932e+03 -2.40516942e+03 -1.98896735e+04
  3.61377097e+04  1.43349833e+05 -1.04942698e+05 -7.68839739e+04
 -2.31922832e+05  1.66405923e+05  1.10462183e+05 -1.13382645e+05
  2.39033328e+04 -3.81333839e+04 -8.96277924e+04  6.05969549e+04
 -8.61303532e+03 -5.35430682e+03  4.66938820e+03  4.28320675e+05
  5.98623672e+04  7.08711026e+04 -1.14340264e+04  1.95945041e+04
 -9.38279305e+02  5.30389229e+04  3.19675584e+04  7.93037325e+03
  7.98987508e+02 -1.11192905e+03 -1.77169188e+03  8.72787470e+02
 -1.13176307e+03 -2.28664922e+02 -7.24351270e+02  1.40091860e+03
  8.38194592e+01  6.99205430e+03 -1.51989762e+03  1.68555367e+04
 -2.59046282e+03 -5.80691683e+03  1.51466626e+02  9.58328502e+03
  4.28765071e+03  1.66885858e+04 -1.41870671e+03  5.32676229e+03
  1.13981070e+03 -5.40593102e+03 -9.81189584e+02  8.32188304e+03
  2.06015440e+03  6.71897663e+02 -3.11220202e+03  3.86774929e+02
  2.11673422e+03 -1.40795299e+04  1.99318225e+04 -3.80377829e+04
  2.66568954e+04  4.27285587e+03 -8.34000506e+04 -2.55243584e+05
 -6.20638046e+04  1.33153800e+05 -2.61142179e+04 -3.05896364e+03
  6.73885335e+03 -2.53400600e+04  4.29312277e+03 -5.39741586e+03
  1.34668557e+03 -2.10887084e+05 -2.15059031e+05 -2.23479358e+05
 -1.12694095e+05 -5.98359708e+04  1.04688759e+05  5.50258651e+04
  3.40698761e+04  1.44525106e+04  9.74660017e+02  2.93434477e+02
  2.04995525e+03  7.20328321e+02  7.97019567e+02  1.58555236e+03
 -8.51085716e+02 -1.12319327e+03 -1.08256705e+03  2.29843929e+04
 -2.33230637e+04  3.12578839e+05  5.48587937e+03  2.67423036e+03
 -1.13443256e+04 -5.25180709e+04  4.45469942e+03  2.50496337e+04
 -2.71767839e+04 -5.30965997e+03  2.16604544e+03 -2.53420578e+04
  9.76449170e+03  2.28837285e+04  1.06209240e+05 -1.33082473e+05
  1.33082248e+05  6.36666580e+04  8.55534810e+03 -7.22217165e+04
 -1.10590953e+04  2.12626388e+04 -1.02033603e+04  6.78574215e+04
 -6.78573302e+04  6.70498848e+04  1.80997748e+04 -1.72920021e+04
 -6.78573114e+04]
iter      4: loss = nan
```

**Comment by sebp** [comment] 2019-11-01 16:23
Using 50 features is probably too much for the basic `CoxnetSurvivalAnalysis` to handle and leads to numerical instability. Have you tried setting `alpha` to a small positive value, e.g. `1e-4`?

**Comment by nd26** [comment] 2019-11-11 10:34
> Using 50 features is probably too much for the basic `CoxnetSurvivalAnalysis` to handle and leads to numerical instability. 

Could you elaborate further on the numerical instability (i.e. what exactly goes wrong)? Is there a less ad-hoc way of dealing with this?

**Comment by sebp** [comment] 2019-11-12 16:33
Fitting `CoxnetSurvivalAnalysis` requires computing the inverse of a matrix, which only exists if the matrix is full rank. With increasing number of features, it is likely that some column will be linearly dependent on other columns, which results in a matrix that's not full rank and breaks optimization. As [mentioned above](https://github.com/sebp/scikit-survival/issues/28#issuecomment-548851698), setting `alpha` to a small value can alleviate this issue.

**Comment by LordFinzenz** [comment] 2020-02-28 10:38
I have 17 features and get _iter 1: loss = -inf_  when using CoxPHSurvivalAnalysis, too. I need to set alpha at least 1.45 to get an output. Is this feasible or too high? And what is "highly correlated" @sebp ? In my data matrix, the highest correlations are 0.79..., 0.72..., etc.

**Comment by sebp** [comment] 2020-03-07 09:56
Unfortunately, it is impossible to say at what value of correlation things fall apart. Standardization is usually helpful.

**Comment by hermidalc** [comment] 2020-03-19 04:08
@sebp I'm a bit confused by what's being said about acceptable choices of `CoxPHSurvivalAnalysis` `alpha`.  I'm also getting a number of the same `RuntimeWarning` warning that have been described here.

Your `CoxPHSurvivalAnalysis` implementation isn't the classical, unpenalized Cox but a better L2-penalized ridge regression Cox is this correct?  So for the choice of `alpha` what is an acceptable range of values?  Is it the same base 10 logspace for ridge regression regularization alpha?  So for `CoxPHSurvivalAnalysis` acceptable `alpha` values would also be e.g. 1e-4 --->1e5 or more for greater regularization?

**Comment by sebp** [comment] 2020-03-20 11:11
It depends on what you set `alpha` to. The default is classical CoxPH without a penalty (`alpha=0`). If `alpha` is non-zero then an l2 penalty is added, which means higher values of alpha will result in more regularization, i.e. coefficients will be forced to be close to zero. What is an acceptable value for `alpha` is debatable, it depends on the scale and number of your features, but 1e-4 sounds like a good start.

**Comment by hermidalc** [comment] 2020-03-20 11:46
> It depends on what you set `alpha` to. The default is classical CoxPH without a penalty (`alpha=0`). If `alpha` is non-zero then an l2 penalty is added, which means higher values of alpha will result in more regularization, i.e. coefficients will be forced to be close to zero. What is an acceptable value for `alpha` is debatable, it depends on the scale and number of your features, but 1e-4 sounds like a good start.

Thank you for the info. My I ask though, for a dataset I’m working on when I did CV to search for `CoxPHSurvivalAnalysis` `alpha` over a log space from 1e-4 to 1e5, it found `alpha` of 1e4 to be the best setting, which is large. I did a literature search to try and understand what are acceptable ranges to this partial log likelihood L2 ridge regression regularization term and really all I found was that `alpha` could be from 0 to inf.

As a test, I also ran `CoxnetSurvivalAnalysis` with `l1_ratio` = 1e-8, so as close to L2 ridge regression penalty as possible to see what the calculated `alphas_` would be for this same dataset and the max alpha in the path (which is computed to be right where all the coefs are zero) was on the order over 1e5. So are very large alpha values acceptable of CV finds they are the best setting?

**Comment by sebp** [comment] 2020-03-20 11:54
Have you used `StandardScalar` before calling `CoxPHSurvivalAnalysis`? That usually takes care of the scale of features. If you still get a high alpha, I don't really know. If GridSearch says it performs best, there must a reason for it, which is specific to your data.

**Comment by hermidalc** [comment] 2020-03-20 12:09
> Have you used `StandardScalar` before calling `CoxPHSurvivalAnalysis`? That usually takes care of the scale of features. If you still get a high alpha, I don't really know. If GridSearch says it performs best, there must a reason for it, which is specific to your data.

Thanks for the pointer. Yes I do always standardize since typically deal with RNA-seq data.

BTW, do you know why in the literature I've seen many article where they use the partial likelihood deviance (I believe also known as partial likelihood ratio) as the CoxPH CV metric to evaluate `alpha`? Are there advantages/disadvantages compare to using  C-index?

**Comment by sebp** [comment] 2020-03-20 12:16
I don't think there is a strong argument for one over the other. With partial likelihood ratio you are directly comparing the losses, which are being optimized, with the c-index you are comparing models based on an external metric.

**Comment by krinetic1234** [comment] 2021-02-16 01:13
Coxnet works greaet for this issue, thanks! You guys should specify this in the intro docs, since the regular CoxAnalysis one doesn't work if you have more than 2 one hot encodings I believe

**Comment by krinetic1234** [comment] 2021-02-16 01:15
@sebp actually, could you explain the difference between CoxNet and CoxPH. Is one more advanced than the other? Would greatly appreciate it..

**Comment by pavopax** [comment] 2021-02-18 15:16
@krinetic1234 CoxPH is not regularized [1] , whereas CoxNet allows you to add (different kinds of) regularization.

There is a very nice and succinct intro about these concepts in the User Guide, see first 2 paragraphs:
https://scikit-survival.readthedocs.io/en/stable/user_guide/coxnet.html

This is documented in the API docs for CoxPH which suggest to "See also CoxnetSurvivalAnalysis".

Together, the API docs and User Guide seem to cover this really well, in my opinion, but feel free to offer additional specific suggestions.


[1] Regularization: https://stats.stackexchange.com/questions/4961/what-is-regularization-in-plain-english

**Comment by 85-hub** [comment] 2023-02-16 00:32
I have the same problem when using CoxPHSurvivalAnalysis to fit a model. Try to drop the first column after using get_dummies to reduce collinearity.
